/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package briscola.Client.GUI;

import briscola.Client.Logic.ClientThread;
import briscola.Main;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Gabriele
 */
public class JFrameError extends javax.swing.JFrame {

    /**
     * Creates new form Error
     */
    
    private Random ran;
    
    public JFrameError() {
        initComponents();
        errorLabel.setLocation(350, 250);
        btnChiudi.setLocation(400, 400);
        ran = new Random();
        Thread changeColor = new Thread(){
            @Override
            public void run(){
                int r, g, b;
                while(true){
                    try {
                        r = ran.nextInt(55) + 200;
                        g = ran.nextInt(55) + 200;
                        b = ran.nextInt(55) + 200;
                        getContentPane().setBackground(new Color(r,g,b));
                        r = ran.nextInt(55) + 200;
                        g = ran.nextInt(55) + 200;
                        b = ran.nextInt(55) + 200;
                        btnChiudi.setBackground(new Color(r,g,b));
                        validate();
                        repaint();
                        sleep(1000);
                    } catch (InterruptedException ex) {}
                }
            }
        };
        changeColor.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorLabel = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 32));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        errorLabel.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        errorLabel.setText("Un giocatore è uscito dalla partita.");

        btnChiudi.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        btnChiudi.setText("CHIUDI");
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btnChiudi))
                            .addComponent(errorLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(errorLabel)
                .addGap(35, 35, 35)
                .addComponent(btnChiudi)
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        this.dispose();
        Main.clientThread = new ClientThread();
        Main.login = new JPanelLogin(Main.clientThread);
        try {
            Main.attesa = new JPanelAttesa();
            Main.new2PGame = new New2PGame(Main.clientThread);
            Main.new4PGame  = new New4PGame(Main.clientThread);
        } 
        catch (InterruptedException ex) {} 
        catch (IOException ex) {}
        Main.menu.add(Main.login);
        Main.menu.setVisible(true);
        Main.menu.pack();
        Main.menu.validate();
        Main.menu.repaint();
        Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnChiudiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameError().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
