/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package briscola.Client.GUI;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Random;

/**
 *
 * @author Gabriele
 */
public class JPanelVincita extends javax.swing.JPanel {

    /**
     * Creates new form JPanelVincita
     */
    
    private Random ran;
    
    public JPanelVincita() {
        initComponents();
        ran = new Random();
        Thread changeColor = new Thread(){
            @Override
            public void run(){
                int r, g, b;
                while(true){
                    try {
                        r = ran.nextInt(55) + 200;
                        g = ran.nextInt(55) + 200;
                        b = ran.nextInt(55) + 200;
                        setBackground(new Color(r,g,b));
                        r = ran.nextInt(55) + 200;
                        g = ran.nextInt(55) + 200;
                        b = ran.nextInt(55) + 200;
                        validate();
                        repaint();
                        sleep(1000);
                    } catch (InterruptedException ex) {}
                }
            }
        };
        changeColor.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.setLocation(300,250);
        panelVincita = new javax.swing.JPanel();
        labelVittoria = new javax.swing.JLabel();
        labelPuntiG1 = new javax.swing.JLabel();
        labelPuntiG2 = new javax.swing.JLabel();
        labelSecondi = new javax.swing.JLabel();

        panelVincita.setBackground(new java.awt.Color(255, 255, 255));

        labelVittoria.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        labelVittoria.setText("Vince: ");

        labelPuntiG1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        labelPuntiG1.setText("Punti G1: ");

        labelPuntiG2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        labelPuntiG2.setText("Punti G2: ");

        labelSecondi.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        labelSecondi.setText("La partita ricomincierà tra 10 secondi");

        javax.swing.GroupLayout panelVincitaLayout = new javax.swing.GroupLayout(panelVincita);
        panelVincita.setLayout(panelVincitaLayout);
        panelVincitaLayout.setHorizontalGroup(
            panelVincitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVincitaLayout.createSequentialGroup()
                .addContainerGap(484, Short.MAX_VALUE)
                .addGroup(panelVincitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVincitaLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(labelVittoria))
                    .addComponent(labelPuntiG2)
                    .addComponent(labelPuntiG1)
                    .addGroup(panelVincitaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(labelSecondi)))
                .addGap(414, 414, 414))
        );
        panelVincitaLayout.setVerticalGroup(
            panelVincitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVincitaLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(labelVittoria)
                .addGap(18, 18, 18)
                .addComponent(labelPuntiG1)
                .addGap(18, 18, 18)
                .addComponent(labelPuntiG2)
                .addGap(75, 75, 75)
                .addComponent(labelSecondi)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1318, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVincita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelVincita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel labelPuntiG1;
    public javax.swing.JLabel labelPuntiG2;
    public javax.swing.JLabel labelSecondi;
    public javax.swing.JLabel labelVittoria;
    public javax.swing.JPanel panelVincita;
    // End of variables declaration//GEN-END:variables
}
