/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package briscola.Client.GUI;

import briscola.Client.Logic.ClientProtocol;
import briscola.Client.Logic.ClientThread;
import briscola.Main;
import static briscola.Main.clientThread;
import briscola.Server.BriskServer;
import briscola.Server.User;
import briscola.Server.UserSocket;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author t.erra
 */
public class JPanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form JPanelLogin
     */
    private String nome;
    private BufferedImage backgroundImage;
    private BufferedImage[] cartaIstruzione;
    private ClientProtocol protocol;

    public JPanelLogin(ClientThread client) {

        initComponents();

        protocol = new ClientProtocol(client);

        BufferedImage[] cartaIstruzione = new BufferedImage[5];

        JPanelCartaIstruzione.setVisible(false);

        this.JLabelScelta.setLocation(this.JLabelScelta.getLocation().x, this.JLabelScelta.getLocation().y - 150);
        this.JLabelGiocatori.setLocation(this.JLabelGiocatori.getLocation().x, this.JLabelGiocatori.getLocation().y + 150);

        JButtonChiudiRegolamento.setVisible(false);

        JButtonAvanti.setOpaque(false);
        JButtonAvanti.setContentAreaFilled(false);
        JButtonAvanti.setBorderPainted(false);

        JButtonIndietro.setOpaque(false);
        JButtonIndietro.setContentAreaFilled(false);
        JButtonIndietro.setBorderPainted(false);

        JButtonInvio.setOpaque(false);
        JButtonInvio.setContentAreaFilled(false); //to make the content area transparent
        JButtonInvio.setBorderPainted(false);

        RBHost.setOpaque(false);
        RBHost.setContentAreaFilled(false);
        RBHost.setBorderPainted(false);

        RBClient.setOpaque(false);
        RBClient.setContentAreaFilled(false);
        RBClient.setBorderPainted(false);

        RBTwoP.setOpaque(false);
        RBTwoP.setContentAreaFilled(false);
        RBTwoP.setBorderPainted(false);

        RBFourP.setOpaque(false);
        RBFourP.setContentAreaFilled(false);
        RBFourP.setBorderPainted(false);

        JButtonRegolamento.setOpaque(false);
        JButtonRegolamento.setContentAreaFilled(false);
        JButtonRegolamento.setBorderPainted(false);

        JButtonChiudiRegolamento.setOpaque(false);
        JButtonChiudiRegolamento.setContentAreaFilled(false);
        JButtonChiudiRegolamento.setBorderPainted(false);

        TextNickname.setOpaque(false);
        TextIP.setOpaque(false);

        jPanelSceltaBg.setVisible(false);

        JPanelCartaIstruzione.setOpaque(false);

        try {
            backgroundImage = ImageIO.read(this.getClass().getResource("../immagini/bg.png"));
        } catch (IOException ex) {
        }
    }

    @Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupGiocatori = new javax.swing.ButtonGroup();
        ButtonGroupServizio = new javax.swing.ButtonGroup();
        buttonGroupBg = new javax.swing.ButtonGroup();
        RBClient = new javax.swing.JRadioButton();
        JLabelScelta = new javax.swing.JLabel();
        RBHost = new javax.swing.JRadioButton();
        JButtonInvio = new javax.swing.JButton();
        TextIP = new javax.swing.JTextField();
        TextNickname = new javax.swing.JTextField();
        JLabelIndirizzo = new javax.swing.JLabel();
        JLabelNome = new javax.swing.JLabel();
        JLabelGiocatori = new javax.swing.JLabel();
        RBTwoP = new javax.swing.JRadioButton();
        RBFourP = new javax.swing.JRadioButton();
        JButtonRegolamento = new javax.swing.JButton();
        JButtonChiudiRegolamento = new javax.swing.JButton();
        JPanelCartaIstruzione = new javax.swing.JPanel();
        JLabelCarta = new IstruzioneCarta();
        JButtonAvanti = new javax.swing.JButton();
        JButtonIndietro = new javax.swing.JButton();
        jPanelSceltaBg = new javax.swing.JPanel();
        jLabelYogioh = new javax.swing.JLabel();
        jLabelPokemon = new javax.swing.JLabel();
        jLabelDigimon = new javax.swing.JLabel();
        RByogioh = new javax.swing.JRadioButton();
        RBpokemon = new javax.swing.JRadioButton();
        RBdigimon = new javax.swing.JRadioButton();
        jButtonSceltaBg = new javax.swing.JButton();

        ButtonGroupServizio.add(RBClient);
        RBClient.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        RBClient.setForeground(new java.awt.Color(255, 255, 255));
        RBClient.setText("Client");
        RBClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBClientActionPerformed(evt);
            }
        });

        JLabelScelta.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        JLabelScelta.setForeground(new java.awt.Color(255, 255, 255));
        JLabelScelta.setText("Selezionare la scelta");

        ButtonGroupServizio.add(RBHost);
        RBHost.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        RBHost.setForeground(new java.awt.Color(255, 255, 255));
        RBHost.setText("Host");
        RBHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBHostActionPerformed(evt);
            }
        });

        JButtonInvio.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        JButtonInvio.setForeground(new java.awt.Color(255, 255, 255));
        JButtonInvio.setText("Invio");
        JButtonInvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonInvioActionPerformed(evt);
            }
        });

        TextIP.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        TextIP.setForeground(new java.awt.Color(255, 255, 255));
        TextIP.setText("127.0.0.1");

        TextNickname.setBackground(new java.awt.Color(0, 0, 0));
        TextNickname.setFont(new java.awt.Font("Cambria Math", 0, 16)); // NOI18N
        TextNickname.setForeground(new java.awt.Color(255, 255, 255));
        TextNickname.setText("pippo");
        TextNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNicknameActionPerformed(evt);
            }
        });

        JLabelIndirizzo.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        JLabelIndirizzo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelIndirizzo.setText("Inserisci l'indirizzo del host");

        JLabelNome.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        JLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        JLabelNome.setText("Inserisci il tuo nome");

        JLabelGiocatori.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        JLabelGiocatori.setForeground(new java.awt.Color(255, 255, 255));
        JLabelGiocatori.setText("Selezionare il numero di giocatori");

        ButtonGroupGiocatori.add(RBTwoP);
        RBTwoP.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        RBTwoP.setForeground(new java.awt.Color(255, 255, 255));
        RBTwoP.setText("2 Giocatori");
        RBTwoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTwoPActionPerformed(evt);
            }
        });

        ButtonGroupGiocatori.add(RBFourP);
        RBFourP.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        RBFourP.setForeground(new java.awt.Color(255, 255, 255));
        RBFourP.setText("4 Giocatori");
        RBFourP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFourPActionPerformed(evt);
            }
        });

        JButtonRegolamento.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        JButtonRegolamento.setForeground(new java.awt.Color(255, 255, 255));
        JButtonRegolamento.setText("Regolamento");
        JButtonRegolamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegolamentoActionPerformed(evt);
            }
        });

        JButtonChiudiRegolamento.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        JButtonChiudiRegolamento.setForeground(new java.awt.Color(255, 255, 255));
        JButtonChiudiRegolamento.setText("Chiudi Regolamento");
        JButtonChiudiRegolamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonChiudiRegolamentoActionPerformed(evt);
            }
        });

        JPanelCartaIstruzione.setPreferredSize(new java.awt.Dimension(233, 403));

        JLabelCarta.setPreferredSize(new java.awt.Dimension(233, 403));

        JButtonAvanti.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        JButtonAvanti.setForeground(new java.awt.Color(255, 255, 255));
        JButtonAvanti.setText("Avanti");
        JButtonAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAvantiActionPerformed(evt);
            }
        });

        JButtonIndietro.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        JButtonIndietro.setForeground(new java.awt.Color(255, 255, 255));
        JButtonIndietro.setText("Indietro");
        JButtonIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonIndietroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelCartaIstruzioneLayout = new javax.swing.GroupLayout(JPanelCartaIstruzione);
        JPanelCartaIstruzione.setLayout(JPanelCartaIstruzioneLayout);
        JPanelCartaIstruzioneLayout.setHorizontalGroup(
            JPanelCartaIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCartaIstruzioneLayout.createSequentialGroup()
                .addComponent(JLabelCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCartaIstruzioneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButtonIndietro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPanelCartaIstruzioneLayout.setVerticalGroup(
            JPanelCartaIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCartaIstruzioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelCartaIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelYogioh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/briscola/Client/Immagini/yugiohIcon.png"))); // NOI18N
        jLabelYogioh.setText("jLabel1");

        jLabelPokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/briscola/Client/Immagini/pokemonIcon.png"))); // NOI18N
        jLabelPokemon.setText("jLabel2");

        jLabelDigimon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/briscola/Client/Immagini/digimonIcon.png"))); // NOI18N
        jLabelDigimon.setText("jLabel3");

        buttonGroupBg.add(RByogioh);
        RByogioh.setText("Yogioh");
        RByogioh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RByogiohActionPerformed(evt);
            }
        });

        buttonGroupBg.add(RBpokemon);
        RBpokemon.setText("Pokemon");

        buttonGroupBg.add(RBdigimon);
        RBdigimon.setText("Digimon");

        jButtonSceltaBg.setText("Scegli");
        jButtonSceltaBg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSceltaBgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSceltaBgLayout = new javax.swing.GroupLayout(jPanelSceltaBg);
        jPanelSceltaBg.setLayout(jPanelSceltaBgLayout);
        jPanelSceltaBgLayout.setHorizontalGroup(
            jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSceltaBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelYogioh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RByogioh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSceltaBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RBpokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDigimon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBdigimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSceltaBgLayout.setVerticalGroup(
            jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSceltaBgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYogioh)
                    .addComponent(jLabelPokemon)
                    .addComponent(jLabelDigimon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSceltaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RByogioh)
                    .addComponent(RBpokemon)
                    .addComponent(RBdigimon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSceltaBg)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RBHost)
                                    .addComponent(RBClient)
                                    .addComponent(JLabelScelta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextIP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelGiocatori)
                                    .addComponent(JLabelIndirizzo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RBFourP)
                                            .addComponent(RBTwoP))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanelSceltaBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(388, 388, 388)))
                        .addComponent(JPanelCartaIstruzione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonChiudiRegolamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JButtonRegolamento)
                        .addGap(448, 448, 448)
                        .addComponent(JButtonInvio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabelNome)
                            .addComponent(JLabelIndirizzo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(TextIP)))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelScelta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBHost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBClient))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelGiocatori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBTwoP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBFourP)))
                        .addGap(31, 31, 31)
                        .addComponent(jPanelSceltaBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(JPanelCartaIstruzione, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonRegolamento)
                    .addComponent(JButtonChiudiRegolamento)
                    .addComponent(JButtonInvio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RBHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBHostActionPerformed
        // TODO add your handling code here:

        this.RBTwoP.setEnabled(true);
        this.RBFourP.setEnabled(true);

        if (RBHost.isSelected()) {

            TextIP.setEnabled(false);
        }
    }//GEN-LAST:event_RBHostActionPerformed

    private void JButtonInvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonInvioActionPerformed
        //codice relative all'avvio del client

        if (TextNickname.getText().isEmpty() && TextIP.getText().isEmpty()) {
            TextNickname.setText("ERROR");
            TextIP.setText("ERROR");
        } else {
            String addr = TextIP.getText();

            nome = TextNickname.getText();
            //  HOST
            if (RBTwoP.isSelected()) {
                BriskServer bs = new BriskServer(2);
                clientThread.connect(addr, 4444);
                clientThread.writeToServer(protocol.createRoom2p(addr));
                clientThread.writeToServer(protocol.enterRoom(nome));
                clientThread.writeToServer(protocol.sendCardBg(Main.new2PGame.bg));
                Main.menu.getContentPane().removeAll();
                Main.menu.add(Main.attesa);
                Main.menu.pack();
                Main.new2PGame.validate();
                Main.new2PGame.repaint();
                Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH);

            }
            if (RBFourP.isSelected()) {
                clientThread.writeToServer(protocol.sendBootstrap(nome));//invio il pacchetto di bootstrap
//              clientThread.writeToServer(protocol.createRoom4p(addr));//invio il pacchetto per la creazione
                clientThread.writeToServer(protocol.sendCardBg(Main.new2PGame.bg));
                Main.menu.getContentPane().removeAll();
                Main.menu.add(Main.attesa);
                Main.menu.pack();
//                Main.new4PGame.validate();
//                Main.new4PGame.repaint();
                Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
                /*
                 Main.menu.getContentPane().removeAll();
                 Main.menu.add(Main.new4PGame);
                 Main.menu.pack();
                 Main.new4PGame.validate();
                 Main.new4PGame.repaint();
                 Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                 */
            }
            //  CLIENT
            if (RBClient.isSelected()) {
                clientThread.connect(addr, 4444);
                clientThread.writeToServer(protocol.sendBootstrap(nome));//invio il pacchetto di bootstrap
                Main.menu.getContentPane().removeAll();
                Main.menu.add(Main.attesa);
                Main.menu.pack();
                Main.new2PGame.validate();
                Main.new2PGame.repaint();
                Main.menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        }
        ;
    }//GEN-LAST:event_JButtonInvioActionPerformed

    private void RBClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBClientActionPerformed
        // TODO add your handling code here

        TextIP.setEnabled(true);

        this.RBTwoP.setEnabled(false);
        this.RBFourP.setEnabled(false);


    }//GEN-LAST:event_RBClientActionPerformed

    private void JButtonRegolamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegolamentoActionPerformed
        // TODO add your handling code here:
        JPanelCartaIstruzione.setVisible(true);
        this.JButtonIndietro.setEnabled(false);
        this.JButtonRegolamento.setEnabled(false);
        this.JButtonRegolamento.setVisible(false);
        this.JButtonChiudiRegolamento.setEnabled(true);
        this.JButtonChiudiRegolamento.setVisible(true);
    }//GEN-LAST:event_JButtonRegolamentoActionPerformed

    private void TextNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNicknameActionPerformed

    private void JButtonAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAvantiActionPerformed
        // TODO add your handling code here:
        IstruzioneCarta label = (IstruzioneCarta) JLabelCarta;

        if (label.immagineSuccessiva() == 2) {
            this.JButtonAvanti.setEnabled(false);
            this.JButtonIndietro.setEnabled(true);
        } else {
            this.JButtonAvanti.setEnabled(true);
            this.JButtonIndietro.setEnabled(true);
        }
    }//GEN-LAST:event_JButtonAvantiActionPerformed

    private void JButtonIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIndietroActionPerformed
        // TODO add your handling code here:
        IstruzioneCarta label = (IstruzioneCarta) JLabelCarta;
        if (label.immaginePrecedente() == 0) {
            this.JButtonIndietro.setEnabled(false);
            this.JButtonAvanti.setEnabled(true);
        } else {
            this.JButtonIndietro.setEnabled(true);
            this.JButtonAvanti.setEnabled(true);
        }
    }//GEN-LAST:event_JButtonIndietroActionPerformed

    private void JButtonChiudiRegolamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonChiudiRegolamentoActionPerformed
        // TODO add your handling code here:
        JPanelCartaIstruzione.setVisible(false);

        this.JButtonRegolamento.setEnabled(true);
        this.JButtonRegolamento.setVisible(true);
        this.JButtonChiudiRegolamento.setVisible(false);
    }//GEN-LAST:event_JButtonChiudiRegolamentoActionPerformed

    private void RByogiohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RByogiohActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RByogiohActionPerformed

    private void jButtonSceltaBgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSceltaBgActionPerformed
        if (RByogioh.isSelected()) {
            Main.new2PGame.bg = 1;
            jPanelSceltaBg.setVisible(false);
//             clientThread.writeToServer(protocol.sendBootstrap(nome));
        } else if (RBpokemon.isSelected()) {
            Main.new2PGame.bg = 2;
            jPanelSceltaBg.setVisible(false);
//             clientThread.writeToServer(protocol.sendBootstrap(nome));
        } else if (RBdigimon.isSelected()) {
            Main.new2PGame.bg = 3;
            jPanelSceltaBg.setVisible(false);
//          clientThread.writeToServer(protocol.sendBootstrap(nome));
        }

    }//GEN-LAST:event_jButtonSceltaBgActionPerformed

    private void RBFourPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFourPActionPerformed
        jPanelSceltaBg.setVisible(true);
    }//GEN-LAST:event_RBFourPActionPerformed

    private void RBTwoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTwoPActionPerformed
        jPanelSceltaBg.setVisible(true);
    }//GEN-LAST:event_RBTwoPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroupGiocatori;
    private javax.swing.ButtonGroup ButtonGroupServizio;
    private javax.swing.JButton JButtonAvanti;
    private javax.swing.JButton JButtonChiudiRegolamento;
    private javax.swing.JButton JButtonIndietro;
    private javax.swing.JButton JButtonInvio;
    private javax.swing.JButton JButtonRegolamento;
    public javax.swing.JLabel JLabelCarta;
    private javax.swing.JLabel JLabelGiocatori;
    private javax.swing.JLabel JLabelIndirizzo;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelScelta;
    private javax.swing.JPanel JPanelCartaIstruzione;
    private javax.swing.JRadioButton RBClient;
    private javax.swing.JRadioButton RBFourP;
    private javax.swing.JRadioButton RBHost;
    private javax.swing.JRadioButton RBTwoP;
    private javax.swing.JRadioButton RBdigimon;
    private javax.swing.JRadioButton RBpokemon;
    private javax.swing.JRadioButton RByogioh;
    private javax.swing.JTextField TextIP;
    private javax.swing.JTextField TextNickname;
    private javax.swing.ButtonGroup buttonGroupBg;
    private javax.swing.JButton jButtonSceltaBg;
    private javax.swing.JLabel jLabelDigimon;
    private javax.swing.JLabel jLabelPokemon;
    private javax.swing.JLabel jLabelYogioh;
    private javax.swing.JPanel jPanelSceltaBg;
    // End of variables declaration//GEN-END:variables
}
