/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package briscola.Client.GUI;

import java.awt.Color;

/**
 *
 * @author t.erra
 */
public class JPanelAttesa extends javax.swing.JPanel{

    /**
     * Creates new form JPanelAttesa
     */
    private  Thread attendi;
    public boolean wait = true;
    
    public JPanelAttesa() throws InterruptedException {
        initComponents();
        this.setBackground(Color.black);
        this.setForeground(Color.red);
        attendi = new Thread(){
            @Override
            public void run(){
                while(wait){
                    JLabelAttesa.setText("Attesa dei giocatori");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {}
                    JLabelAttesa.setText("Attesa dei giocatori.");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {}
                    JLabelAttesa.setText("Attesa dei giocatori..");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {}
                    JLabelAttesa.setText("Attesa dei giocatori...");
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {}
                }
            }
        };
        attendi.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelAvviso = new javax.swing.JPanel();
        JLabelAttesa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        JPanelAvviso.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 51)));
        JPanelAvviso.setRequestFocusEnabled(false);

        JLabelAttesa.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        javax.swing.GroupLayout JPanelAvvisoLayout = new javax.swing.GroupLayout(JPanelAvviso);
        JPanelAvviso.setLayout(JPanelAvvisoLayout);
        JPanelAvvisoLayout.setHorizontalGroup(
            JPanelAvvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAvvisoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JLabelAttesa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        JPanelAvvisoLayout.setVerticalGroup(
            JPanelAvvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAvvisoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(JLabelAttesa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(JPanelAvviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(JPanelAvviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JLabelAttesa;
    private javax.swing.JPanel JPanelAvviso;
    // End of variables declaration//GEN-END:variables

 
}
